---

- name: "create the local backup path {{ backup_mongo_local_path }}"
  file: path={{ backup_mongo_local_path }} state=directory mode=0755 recurse=yes

- include: configure_backup.yml
  when: not restore_only

- name: "Add mongodb restore script /usr/bin/mongo-restore.sh"
  template: src="{{ ansible_template_path_legacy }}mongodb/mongo-restore.sh.j2" dest=/usr/bin/mongo-restore.sh owner=root group=root mode=0755
