- name: "create the local backup path {{ backup_mysql_local_path }}"
  file: path={{ backup_mysql_local_path }} state=directory mode=0755 recurse=yes

- include: configure_backup.yml
  when: not restore_only

- name: "Add MySQL db restore script /usr/bin/{{ restore_mysql_script }}.sh"
  template: src="{{ ansible_template_path_legacy }}mysql/mysql-restore.sh.j2" dest=/usr/bin/{{ restore_mysql_script }}.sh owner=root group=root mode=0755
